language: c

dist: xenial
os: linux

addons:
  apt:
    sources:
    - sourceline: 'deb http://de.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse'
    - sourceline: 'deb-src http://de.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse'
    packages:
    # - g++-7
    - libtool-bin
    - libtermkey-dev
    update: true

install:
- gem install mdl
- pip install proselint --user

script:
- make clean
# build
- make all
- make examples
# test
- make test
# lint
- mdl *.md
- proselint *.md
