language: c
sudo: required

dist: xenial
os: linux

addons:
  apt:
    packages:
    # - g++-7
    - libtool-bin
    - screen

install:
- gem install mdl
- pip install proselint --user
- wget http://www.leonerd.org.uk/code/libtermkey/libtermkey-0.22.tar.gz
- tar -xzvf libtermkey-0.22.tar.gz
- ( \cd libtermkey-0.22; make all; sudo make PREFIX=/usr install; )

cache: pip

script:
- make clean
# build
- make all
- make examples
# test
- make test
# lint
- mdl *.md
- proselint *.md
