language: c

dist: xenial
os: linux

addons:
  apt:
    # sources:
      # - ubuntu-toolchain-r-test
    packages:
      # - g++-7
      - automake
      - autoconf
      - libtermkey-dev

install:
  - gem install mdl
  - pip install proselint --user

script:
  - make clean
  # build
  - make all
  - make examples
  # test
  - make test
  # lint
  - mdl *.md
  - proselint *.md
