language: c
sudo: required

dist: xenial
os: linux

addons:
  apt:
    packages:
    # - g++-7
    - libtool-bin
    - screen

install:
- gem install mdl
- pip install proselint --user
- source .travis-deps.sh

cache: pip

script:
- make clean
# build
- make all
- make examples
# test
- make test
# lint
- mdl *.md
- proselint *.md
