language: c
sudo: required

dist: xenial
os: linux

addons:
  apt:
    packages:
    # - g++-7
    - libtool-bin

install:
- gem install mdl
- pip install proselint --user
- wget http://www.leonerd.org.uk/code/libtermkey/libtermkey-0.22.tar.gz
- tar -xzvf libtermkey-0.22.tar.gz
- make -C libtermkey-0.22 all
- sudo make -C libtermkey-0.22 install

cache: pip

script:
- make clean
# build
- make all
- make examples
# test
- make test
# lint
- mdl *.md
- proselint *.md
